import type { CSSProperties } from 'react'
import type { WidgetRenderProps } from './types'
import type { DocData } from './doc'

/** kbz.doc renderer — the pre-sanitized HTML from doc.ts (a bounded markdown subset, all text escaped, links
 *  http(s)-only). dangerouslySetInnerHTML is safe here precisely because the HTML was generated by our renderer
 *  from escaped text — no untrusted markup ever reaches it. */
export default function DocWidget({ data, fill }: WidgetRenderProps<DocData>) {
  return (
    <div style={{ ...card, maxWidth: fill ? '100%' : 'min(360px, 100%)', maxHeight: fill ? '100%' : 320 }}>
      {data.title && <div style={titleStyle}>{data.title}</div>}
      <div className="kw-doc-body" style={body} dangerouslySetInnerHTML={{ __html: data.html }} />
    </div>
  )
}

const card: CSSProperties = { background: '#fff', color: '#1a1a1a', borderRadius: 12, padding: '14px 16px', overflow: 'auto', minWidth: 0, boxShadow: '0 1px 4px rgba(0,0,0,.25)', width: '100%' }
const titleStyle: CSSProperties = { font: '800 16px/1.3 system-ui, sans-serif', marginBottom: 8 }
// The inner HTML uses h3-h5/p/ul/ol/li/code/pre/blockquote/a/strong/em/hr — styled via a scoped CSS string the
// widget injects (kw-doc-body), so we keep readable typography without per-tag inline styles.
const body: CSSProperties = { font: '400 13.5px/1.6 system-ui, sans-serif' }
